#!/bin/bash -eu

readonly MAX_STARTUP_CHECK_ATTEMPTS="11"

readonly command=${1:?}
readonly jar_path=${2:?}
readonly build_dir=${3:?}

readonly startup_command="java -jar ${jar_path}"
readonly log_path="$build_dir/test-server.log"
readonly pid_path="$build_dir/test-server.pid"

get_server_pid() {
    cat ${pid_path}
}

wait_for_startup() {
    local last_exit_code=-1
    local attempts=0

    echo " >>> Esperando inicializacao completa do servidor..."

    while [ ! "$last_exit_code" -eq "0" ]
    do
        last_exit_code=$(curl -s localhost:8080 > /dev/null 2>&1; echo $?)

        attempts=$((attempts+1))

        if [ "$attempts" -eq "$MAX_STARTUP_CHECK_ATTEMPTS" ]; then
            echo " >>> O servidor nao foi inicializado corretamente. Verifique os logs em $log_path"
            exit 1
        fi

        sleep 1
    done

    echo " >>> Servidor iniciado com pid $(get_server_pid)"

}

case ${command} in
    start)
        ${startup_command} > ${log_path} 2>&1 &
        echo $! > ${pid_path}
        wait_for_startup
        ;;
    stop)
        echo " >>> Parando servidor com pid $(get_server_pid)"
        kill -9 $(get_server_pid)
        rm ${pid_path} ${log_path}
        echo " >>> Sevidor parado com sucesso"
        ;;
    *)
        echo " >>> Opcao indisponivel. Tente uma das seguintes: start | stop"
        exit 1
        ;;
esac
